# Generated by Django 4.2 on 2024-06-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RAGMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Chat_Id", models.IntegerField(default=0)),
                ("Title", models.CharField(max_length=50)),
                ("File_Name", models.CharField(max_length=250)),
                ("conversations_For_Ai", models.JSONField(default=list)),
                ("conversations_For_User", models.JSONField(default=list)),
            ],
        ),
    ]
